FROM python:3.7-buster
RUN apt-get update && apt-get install -y \
	libcurl4-openssl-dev \
	libssl-dev


RUN useradd -ms /bin/bash beelurer
USER beelurer
WORKDIR /home/beelurer/

COPY requirements.txt .
RUN python3.7 -m pip install -r requirements.txt

COPY src/ app/

CMD ['python3.7' main.py']
